apiVersion: apps/v1
kind: Deployment
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service_name
  template:
    metadata:
      labels:
        app: service_name
    spec:
      containers:
        - name: workspace
          image: container_image
          ports:
            - containerPort: container_port
          env:
            - name: VNC_PW
              value: service_password
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: service_name
  labels:
    app: service_name
spec:
  selector:
    app: service_name
  ports:
    - name: vnc
      port: container_port
      targetPort: container_port
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service_name
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: ingress_class
  rules:
    - http:
        paths:
          - path: /service_name(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: service_name
                port:
                  number: container_port


